title Процесс записи информации на DVD-диск
actor "Пользователь"

Пользователь -- (Получение данных)
(Получение данных) --> (Проверка свободного места)
(Проверка свободного места) --> (Выполнение записи)
(Выполнение записи) --> (Выполнение проверки)

rectangle "Успешная запись на диск"{
(Выполнение проверки) --> (Запись успешна)
}

rectangle "Недостаточно места на диске"{
(Выполнение проверки) --> (Недостаточно места)
}

rectangle "Запись после финализации"{
(Недостаточно места) --> (Финализация записи)
(Финализация записи) --> (Запись после финализации)
}

rectangle "Повреждение диска"{
(Выполнение проверки) --> (Повреждение диска)
}

rectangle "Ошибка при верификации"{
(Выполнение проверки) --> (Ошибка верификации)
}


(Запись успешна) --> (Завершение процесса)
(Запись после финализации) --> (Завершение процесса)
(Повреждение диска) --> (Завершение процесса)
(Ошибка верификации) --> (Завершение процесса)
